### ISSUE TITLE
Issue with JFrog Xray scanning of .NET 5 project

### ISSUE THREAD

**Issue by nemanjamaricfincore** [jfrog/jfrog-visual-studio-extension#26]
Please find error below:

[19/07/2022 14:48:08] An error occurred while sending the request.
[19/07/2022 14:48:08]    at JFrogVSExtension.HttpClient.HttpUtils.<GetVersionAsync>d__2.MoveNext() in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\Utils\HttpClient\HttpUtils.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JFrogVSExtension.Tree.TreeViewModel.<LoadAsync>d__21.MoveNext() in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\UI\Panel\Tree\TreeViewModel.cs:line 72
[19/07/2022 14:48:09] An error occurred while sending the request.
[19/07/2022 14:48:09]    at JFrogVSExtension.HttpClient.HttpUtils.<GetVersionAsync>d__2.MoveNext() in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\Utils\HttpClient\HttpUtils.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JFrogVSExtension.Tree.TreeViewModel.<LoadAsync>d__21.MoveNext() in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\UI\Panel\Tree\TreeViewModel.cs:line 72

I tried this with multiple projects that we have and the error is the same. Can you please advice?

Many thanks

**Comment by sdvck** [comment]
Hi,

I have experienced similar error when running JFrog analysis from VS JFrog Extension, with the stacktrace:

[20/07/2022 11:03:16] Object reference not set to an instance of an object.
[20/07/2022 11:03:16]    at JFrogVSExtension.Data.DataService.populateRootElements(Projects projects) in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\UI\Panel\DataService.cs:line 69
   at JFrogVSExtension.Tree.TreeViewModel.<LoadAsync>d__21.MoveNext() in C:\robi\releasedir\jfrog-visual-studio-extension\JFrogVSExtension\UI\Panel\Tree\TreeViewModel.cs:line 114

I am using Visual Studio Professional 2019, Version 16.9.2.
JFrog Extension version is 1.1.0

Can you please advice?

Best regards, Stefan

**Comment by talarian1** [comment]
Hi @nemanjamaricfincore, @sdvck 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this issue.
It seems like this is a problem with Xray itself - a fix will be included in the next Xray version.

**Comment by nemanjamaricfincore** [comment]
Hi @talarian1,

Thank you so much for looking into this. Any idea about timelines and when we can expect new version of XRay?
Thanks,
Nemanja

**Comment by eyalbe4** [comment]
The fix is included in version 3.54.5 which should become available shortly @nemanjamaricfincore.

**Comment by talarian1** [comment]
Hi @nemanjamaricfincore @sdvck, Dose the Xray upgrade solve the issue?
